apiVersion: v1
kind: Service
metadata:
  labels:
     app: nginx
  name: nginx
  namespace: default
spec:
  selector:
     app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort  
                                  
